### ISSUE TITLE
Building addin in windows/appveyor

### ISSUE THREAD

**Issue by jzeferino** [agc93/cake-xs#1]
Hy there, this is not an issue related with your addin, but I'm building a addin.
I've recently implemented a addin and added cake script to build it. It works fine on osx but in windows (local machine) / appveyor I got this error:

> \src\packages\MonoDevelop.Addins.0.3.8\build\net40\MonoDevelop.Addins.targets(84,5): error : Bin directory not found: C:\Program Files (x86)\Xamarin Studio\bin

I've tried to build your project (to check if the problem only occur in my code) and in my local machine osx and it build like mine addin build, but, in my local windows machine the error is the same.

Looking at MonoDevelop.Addins.targets line 84 I guess this is related with mdtool.exe.
I don't have the folder `C:\Program Files (x86)\Xamarin Studio\bin` neither the mdtool.exe on windows.

**EDIT**: I copied all the files from `/Applications/Xamarin Studio.app/Contents/Resources/lib/monodevelop/bin` to `C:\Program Files (x86)\Xamarin Studio\bin` and i was able to build the project. I did only this for testing. 

How do you solved this?

**Comment by agc93** [comment]
@jzeferino I don't really know what you're building, how you're building it or any context for your issue. Are you using a Cake script?

Is this project on GitHub or anything?

**Comment by jzeferino** [comment]
I updated my first post to be a little bit more clear, but anyway I will try to be more clear. 

I implemented a addin and used cake to compile it. I can compile it in my machine but when I added it to Appveyor or tryed to compile it in my other windows machine it wont compile with this error:

> \src\packages\MonoDevelop.Addins.0.3.8\build\net40\MonoDevelop.Addins.targets(84,5): error : Bin directory not found: C:\Program Files (x86)\Xamarin Studio\bin

Since I faced this problem I tryed to compile your project in my windows machine and got the same error. (Note in OSX it compiles).

Its more clear for you now?

Will put the project in github soon.

Note: this issue its related to https://github.com/Redth/Cake.Xamarin/issues/10

**Comment by agc93** [comment]
~~I don't think the AppVeyor environment will have Xamarin Studio or MonoDevelop installed, so likely that error is exactly what it sounds like: the path to MD/XS can't be found..~~

**EDIT**: Judging by [this project](https://ci.appveyor.com/project/mrward/monodevelop-paket-addin/build/0.0.1.10), looks like AppVeyor *might* have MonoDevelop installed, but it may not be Xamarin Studio (which would change the path).

You need to have both MonoDevelop (or Xamarin Studio) and MonoDevelop.Addins installed in order to build a MonoDevelop addin (much the same as Visual Studio Extensions which need both VS and VSIX tools).

**Comment by jzeferino** [comment]
Your correct. But Xamarin Studio is not available for Windows that I know.

From the addin maker [github](https://github.com/mhutch/MonoDevelop.AddinMaker) we have:

> Because loading the Addin Maker in MD/XS requires itself to be installed, scripts are provided to build and install it from the commandline. Simply run Install.bat (Windows) or make install (Mac, Linux).

We must configure the appveyor.yml to clone the repo and install it. Take a look at [this](https://github.com/mrward/monodevelop-paket-addin/blob/master/appveyor.yml).

But anyway from the error:
> src\packages\MonoDevelop.Addins.0.3.8\build\net40\MonoDevelop.Addins.targets(84,5): error : Bin directory not found: C:\Program Files (x86)\Xamarin Studio\bin

MonoDevelop.Addins.targets(84,5) is looking for the  C:\Program Files (x86)\Xamarin Studio\bin witch don't exist and I guess we cant install Xamarin Studio in windows.

For now I only can build and Pack in my OSX. Do you have any suggestion to at least build the Addin on AppVeyor?

**Comment by agc93** [comment]
Xamarin Studio Community (6.1.2) is available for Windows, it's just the download links aren't on the website for the last little while.

That AppVeyor file you linked to doesn't install MonoDevelop or Addin Maker anywhere, it just looks like his solution builds fine without them being installed (only GTK# looks to be required).

If you're having issues with the Cake part of it, you may need to raise an issue on the [Cake repo](http://github.com/cake-build/cake) (this is just an experimental addin for XS), but otherwise no, I'm afraid I don't know. Once you get MSBuild to build your solution, adding it to Cake is generally pretty simple.

**Comment by jzeferino** [comment]
The issue ins't related with Cake at all. I never said thats the problem.
The problem is compiling the addin on windows. I can't compile mine, neither yours.

And yes, I don't have XS installed in windows. Will try that.
But anyway, if it work I will have to make AppVeyor install xamarin studio too. That sucks a bit.

Thanks for the feedback.

**Comment by agc93** [comment]
Okay was checking if it was Cake since you raised an issue against this add-in. My extension builds fine on Windows but that's with Xamarin Studio installed.

**Comment by jzeferino** [comment]
Thanks for your time.

Your solution compile in AppVeyor?

**Comment by agc93** [comment]
No, I'm not currently building in AppVeyor as this is still experimental.

**Comment by jzeferino** [comment]
If you ended up compiling in Appveyor let me know.

**Comment by jzeferino** [comment]
To build on AppVeyor we need to instal Xamarin Studio witch need gtk, so heres my solution:

```xml
install:
  - if not exist gtk-sharp-2.12.38.msi appveyor DownloadFile http://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.38.msi
  - msiexec /i gtk-sharp-2.12.38.msi /qn /norestart
  - if not exist XamarinStudio-6.1.2.44.msi appveyor DownloadFile https://dl.xamarin.com/MonoDevelop/Windows/XamarinStudio-6.1.2.44.msi
  - msiexec /i XamarinStudio-6.1.2.44.msi /qn /norestart
```
Full [AppVeyor.xml](https://github.com/jzeferino/jzeferino.XSAddin/blob/9b357b87f2b7aed25df79e2d236e02d7654e1f70/appveyor.yml)

Anyway I still have issues Packaging it on windows. Locally it works fine but in AppVeyor I got this:

> 
> Xamarin Studio Add-in Setup Utility
> ERROR: Could not read add-in file: C:/projects/jzeferino-xsaddin/src/jzeferino.XSAddin/bin/Release/jzeferino.XSAddin.dll
> INFO [2017-02-10 15:01:26Z]: Did not find previous version from which to migrate data
> Finished executing task: Pack

And yes, the file is there.
If you know something about this please let me know.

**Comment by agc93** [comment]
@jzeferino Like I said, I don't know anything about building on AppVeyor, this addin is not currently built on AppVeyor, I use Cake for building, and I don't know anything about your own addin or how it builds.

**Comment by jzeferino** [comment]
Thank you.
